### ISSUE TITLE
Deep copy vs. shallow copy vs. shared_ptr

### ISSUE THREAD

**Issue by lrosenth** [dasch-swiss/sipi#123]
We have to carefully look where we need deep copies of SipiImage, SipiXmp, SipiExiv etc. classes. We should provide copy constructors and assignment operator overloads creating deep copies of these instances!

**Comment by benjamingeer** [comment]
This is difficult for me to do because I don't understand the life cycle of these objects. Could you write a design document describing what happens when Sipi processes a request, i.e. what objects are created, how they are used by other objects, and when they are destroyed? Then I think we would have the answer. Now that I've merged the Sphix documentation, you could add this as an `rst` file under `manual`. Here's a quick reference to RST syntax: http://docutils.sourceforge.net/docs/user/rst/quickref.html. To make your file appear in the table of contents, you just need to reference it in `index.rst`.

**Comment by lrosenth** [comment]
Yes, I'll do this...

Lukas

Sent from my iPad

On 9 Feb 2017, at 11:11, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


This is difficult for me to do because I don't understand the life cycle of these objects. Could you write a design document describing what happens when Sipi processes a request, i.e. what objects are created, how they are used by other objects, and when they are destroyed? Then I think we would have the answer. Now that I've merged the Sphix documentation, you could add this as an rst file under manual. Here's a quick reference to RST syntax: http://docutils.sourceforge.net/docs/user/rst/quickref.html. To make your file appear in the table of contents, you just need to reference it in index.rst.
