### ISSUE TITLE
Does Sipi currently support audio files?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/sipi#222]
And if so, what should be the file format supported in order to ensure long-term archiving in Knora?

I have had a look at the CINES (cool) tool to validate a format here: https://facile.cines.fr/

And also at the KOST-CECO recommendations here [https://kost-ceco.ch/wiki/whelp/Cfa/index.php](url) but I would like to have to insight on this matter, as we have a project with a few audio files (and various formats: .m4a, .mp3).

**Comment by tobiasschweizer** [comment]
No, Sipi only supports images and some text file types.

Please see https://github.com/dhlab-basel/Sipi/blob/472c694d20aa283839a70b75192f3c20b91a10ad/scripts/get_mediatype.lua#L42

This is used here: https://github.com/dhlab-basel/Sipi/blob/472c694d20aa283839a70b75192f3c20b91a10ad/scripts/convert_from_binaries.lua#L84

The basic idea is that Sipi checks the magic number of a file and the consistency of the mime type and the file extension.

More non-image file types might by added. But probably we should find a more convenient way to do this.

**Comment by mrivoal** [comment]
Thanks for the answer. 

But the last time we talked to @lrosenth, I think he said that Sipi was already able to handle files like PDF (even though @loicjaouen didn't find anything PDF-related within the lua files you mention). 

And if so, I imagined that Sipi may not be that far from being able to support audio files as well... But maybe it is still a work-in-progress?

**Comment by tobiasschweizer** [comment]
Sipi just serves non image files as they are. It can serve any file.

But the current design of the routes (in `scripts`) requires explicit support in Lua. However, this is not a restriction of the Sipi core application.

**Comment by lrosenth** [comment]
Ok, some clarifications:

SIPI does support any file type (PDF, mp4, mp3, wav etc.), but not using the normal IIIF path (since IIIF does not support these files). However SIPI incorporates a "normal" webserver which is also configurable in sipi.init.lua. Through this webserver it is able to serve an filetype including also (in html) embedded lua (*.elua). See in the "server"-directory for examples!

This it is absolutely possible to serve an filetype, but of course not using the normal IIIF syntax (because this makes no sense).

If the IIIF-syntax for a file looks like this:

http//sipi.myserver.org/images/full/full/0/default.jpg<http://sipi.myserver.org/images/full/full/0/default.jpg>,

the syntax to access a "normal" file (such as an audio or vide file), the syntax would look like (depending on configuration):

http://sipi.myserver.org/server/sound/my_top10.wav

SIPI does not yet support range headers, but it will be straight forward to implement this! (If You need it please let me know).

Hope this helps,
Lukas

Am 27.11.2017 um 11:12 schrieb Marion Rivoal <notifications@github.com<mailto:notifications@github.com>>:


And if so, what should be the file format supported in order to ensure long-term archiving in Knora?

I have had a look at the CINES (cool) tool to validate a format here: https://facile.cines.fr/

And also at the KOST-CECO recommendations here https://kost-ceco.ch/wiki/whelp/Cfa/index.php<x-msg://5/url> but I would like to have to insight on this matter, as we have a project with a few audio files (and various formats: .m4a, .mp3).

**Comment by mrivoal** [comment]
Ok, thanks @lrosenth for the clarification. This is somewhat what I understood. But let's find 5 minutes tomorrow to discuss this point and what it would take to have audiofiles implemented.

**Comment by lrosenth** [comment]
Sipi now supports any binary files and also supports the range header. Thus video and audio files may be streamed from sipi.

**Comment by mrivoal** [comment]
Great news, thanks! 

Now I guess it also raises the question as to which formats we will accept for these files because I guess we should accept only the most reliable ones on the long run.

The documentation is still elusive on this matter : https://docs.knora.org/paradox/01-introduction/data-formats.html.
