### ISSUE TITLE
Https mixed content problem using sipi

### ISSUE THREAD

**Issue by ubunibas** [dasch-swiss/sipi#273]
When using https the info.json still contains a http link. This might be the reason why when we display our  manifests (e.g. https://ub-iiifpresentation.ub.unibas.ch/impresso/shz-1891-01-03-a-issue/manifest/) with viewers like Universalviewer or Mirador we have mixed content problems because these viewers load the info.json and use the @id for fetching high-res-images.

![sipi_https_problem](https://user-images.githubusercontent.com/17339984/49217286-76191280-f3cd-11e8-8f8c-1c97dbacdcba.PNG)

**Comment by lrosenth** [comment]
Ok - thanks! I’ll check that an change info,json accordingky to the protocol used. Should be available soon!

Von meinem iPhone gesendet

Am 29.11.2018 um 12:02 schrieb ubunibas <notifications@github.com<mailto:notifications@github.com>>:


When using https the info.json still contains a http link. This might be the reason why when we display our manifests (e.g. https://ub-iiifpresentation.ub.unibas.ch/impresso/shz-1891-01-03-a-issue/manifest/) with viewers like Universalviewer or Mirador we have mixed content problems because these viewers load the info.json and use the @id<https://github.com/id> for fetching high-res-images.

[sipi_https_problem]<https://user-images.githubusercontent.com/17339984/49217286-76191280-f3cd-11e8-8f8c-1c97dbacdcba.PNG>
