### ISSUE TITLE
question: controlling iiif parameters

### ISSUE THREAD

**Issue by Sewdn** [dasch-swiss/sipi#321]
Hi,

we are evaluating switching from iiifserver from Klokantech (https://github.com/klokantech/iiifserver) to sipi, because sipi seems far more feature complete with regards to the iiif spec. Thanks for this great software!

However, we are experiencing some issues in configuring the server to optimize the tiles that are being used when panning and zooming with an iiif compliant client like Openseadragon.

We are testing with the default configuration provided in this docker: dhlabbasel/sipi:develop
Currently, we see tiles are being upserved 1024x1024px where we would like them to be 256x256px. Also, we have no control on the zoom levels where we control when to use different 256x256px tiles.

In comparison, out-of-the box iiifserver from Klokantech, provides this info.json:
```
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://iiif.textus.io/Dymphna-na/",
  "protocol" : "http://iiif.io/api/image",
  "width" : 7273,
  "height" : 11520,
  "sizes" : [
     { "width" : 113, "height" : 180 },
     { "width" : 227, "height" : 360 },
     { "width" : 454, "height" : 720 }
  ],
  "tiles" : [
     { "width" : 256, "height" : 256, "scaleFactors" : [ 1, 2, 4, 8, 16, 32, 64 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray" ],
       "supports" : ["regionByPct","regionSquare","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring"] }
  ]
}
```

Default config for sipi, provides this out-of-the-box info.json for the same source, where no info is provided about tiles, scalefactors, and the available sizes are much larger.

My question: How to change the output of this info.json files?

```
{
   "@context": "http://iiif.io/api/image/2/context.json",
   "@id": "http://sipi.textus.io/iiif/Dymphna-na",
   "protocol": "http://iiif.io/api/image",
   "width": 7273,
   "height": 11520,
   "sizes": [
      { "width": 3637, "height": 5760 },
      { "width": 1819, "height": 2880 },
      { "width": 910, "height": 1440 },
      { "width": 455, "height": 720 }
   ],
   "profile": [
      "http://iiif.io/api/image/2/level2.json",
      {
         "formats": [ "tif", "jpg", "png", "jp2", "pdf" ],
         "qualities": [ "color", "gray" ],
         "supports": [
            "color",
            "cors",
            "mirroring",
            "profileLinkHeader",
            "regionByPct",
            "regionByPx",
            "rotationArbitrary",
            "rotationBy90s",
            "sizeAboveFull",
            "sizeByWhListed",
            "sizeByForcedWh",
            "sizeByH",
            "sizeByPct",
            "sizeByW",
            "sizeByWh"
         ]
      }
   ]
}
```

Furthermore we notice that no manifest.json is provided out-of-the-box by sipi. It should be available next to the info.json, no?

Thanks for looking into this!

Kind regards,
Pieter

**Comment by lrosenth** [comment]
Hi,

I‘ll have a Look at it. Probably I can add this Go the configuration file.
Do You know the Parameters that have been used to create the J2K Files?

Give me about 2 Werks to create a fix!
Lukas

Lukas Rosenthaler

Von meinem iPad gesendet

Am 28.02.2020 um 10:30 schrieb Pieter Soudan <notifications@github.com>:

﻿

Hi,

we are evaluating switching from iiifserver from Klokantech (https://github.com/klokantech/iiifserver) to sipi, because sipi seems far more feature complete with regards to the iiif spec. Thanks for this great software!

However, we are experiencing some issues in configuring the server to optimize the tiles that are being using when panning and zooming with an iiif compliant client like Openseadragon.

We are testing with the default configuration provided in this docker: dhlabbasel/sipi:develop
Currently, we see tiles are being upserved 1024x1024m where we would like them to be 256x256. Also, we have no control on the zoom levels where we control when to use different 256x256 tiles.

In comparison, out-of-the box iiifserver from Klokantech, provides this info.json:

{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "http://iiif.textus.io/Dymphna-na/",
  "protocol" : "http://iiif.io/api/image",
  "width" : 7273,
  "height" : 11520,
  "sizes" : [
     { "width" : 113, "height" : 180 },
     { "width" : 227, "height" : 360 },
     { "width" : 454, "height" : 720 }
  ],
  "tiles" : [
     { "width" : 256, "height" : 256, "scaleFactors" : [ 1, 2, 4, 8, 16, 32, 64 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray" ],
       "supports" : ["regionByPct","regionSquare","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring"] }
  ]
}


Default config for sipi, provides this out-of-the-box info.json for the same source, where no info is provided about tiles, scalefactors, and the available sizes are much larger.

My question: How to change the output of this info.json files?

{
   "@context": "http://iiif.io/api/image/2/context.json",
   "@id": "http://sipi.textus.io/iiif/Dymphna-na",
   "protocol": "http://iiif.io/api/image",
   "width": 7273,
   "height": 11520,
   "sizes": [
      { "width": 3637, "height": 5760 },
      { "width": 1819, "height": 2880 },
      { "width": 910, "height": 1440 },
      { "width": 455, "height": 720 }
   ],
   "profile": [
      "http://iiif.io/api/image/2/level2.json",
      {
         "formats": [ "tif", "jpg", "png", "jp2", "pdf" ],
         "qualities": [ "color", "gray" ],
         "supports": [
            "color",
            "cors",
            "mirroring",
            "profileLinkHeader",
            "regionByPct",
            "regionByPx",
            "rotationArbitrary",
            "rotationBy90s",
            "sizeAboveFull",
            "sizeByWhListed",
            "sizeByForcedWh",
            "sizeByH",
            "sizeByPct",
            "sizeByW",
            "sizeByWh"
         ]
      }
   ]
}


Furthermore we notice that no manifest.json is provided out-of-the-box by sipi. It should be available next to the info.json, no?

Thanks for looking into this!

Kind regards,
Pieter

**Comment by Sewdn** [comment]
Hi Lukas,

thanks for your response.
In the iiif spec, sizes and tiles are defined as optional technical properties:
https://iiif.io/api/image/2.1/#technical-properties

They depict the available preconfigured tilesizes that are available on the server.

Since SIPI doesn't do any preprocessing (I presume) on the uploaded images, no out-of-the-box tiles are being made available. All is done on demand, right? And therefor it makes sence, not to provide any info about available tiles.

IIIFServer (and therefor IIPImage https://iipimage.sourceforge.io/), do preprocess uploaded images. They seem to be converted as J2K images, and I presume that all different resized images for all preconfigured zoom-levels are stored within this format. This makes IIPImage blazing fast when serving tiles for certain zoom levels, since they only need to be cropped (and stored to cache), no downsampling is needed when tiles are being requested on demand.

I'm willing to contribute to sipi, to make this same approach available. Could you please give me some pointers where this would fit in in the source?

Thanks!

**Comment by lrosenth** [comment]
Hi Pieter,

Yes, wonderful. Right now I‘m in London (a few days of vacation), I‘ll be back next thursday and will contact You.

Any contribution is highly welcome!

Lukas Rosenthaler

Von meinem iPad gesendet

Am 28.02.2020 um 16:05 schrieb Pieter Soudan <notifications@github.com>:

﻿

Hi Lukas,

thanks for your response.
In the iiif spec, sizes and tiles are defined as optional technical properties:
https://iiif.io/api/image/2.1/#technical-properties

They depict the available preconfigured tilesizes that are available on the server.

Since SIPI doesn't do any preprocessing (I presume) on the uploaded images, no out-of-the-box tiles are being made available. All is done on demand, right? And therefor it makes sence, not to provide any info about available tiles.

IIIFServer (and therefor IIPImage https://iipimage.sourceforge.io/), do preprocess uploaded images. They seem to be converted as J2K images, and I presume that all different resized images for all preconfigured zoom-levels are stored within this format. This makes IIPImage blazing fast when serving tiles for certain zoom levels, since they only need to be cropped (and stored to cache), no downsampling is needed when tiles are being requested on demand.

I'm willing to contribute to sipi, to make this same approach available. Could you please give me some pointers where this would fit in in the source?

Thanks!

**Comment by lrosenth** [comment]
The next release of SIPI expected in a 2-3 weeks will support IIIF Image API 3.0 level 2.
The info.json will reflect the tiling of the underlying image and add these parameters to info.json.
