### ISSUE TITLE
Image conversion error on Ubuntu

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/sipi#99]
Using the `python-test` branch:

```
$ make check

...

TestConversions: Sipi should convert LeavesC.jp2 to JPG F

...

E           conftest.SipiTestError: Downloaded image /tmp/tmp_oh23btb.jpg is different from expected image /home/benjamin/git/Sipi/test/_test_data/images/knora/LeavesC.jpg (wrote /home/benjamin/git/Sipi/test/sipi.log):
E           Image Difference (MeanAbsoluteError):
E                      Normalized    Absolute
E                     ============  ==========
E                Red: 0.0000011204        0.1
E              Green: 0.0000012358        0.1
E               Blue: 0.0000016248        0.1
E              Total: 0.0000013270        0.1
```

**Comment by lrosenth** [comment]
Hi Ben,

A JPG is *never* the same as a lossless J2K, since JPG is lossy and does change the pixel values… However the error is small, if the compression rate is not too high (SIPI uses 0.8 by default where 1.0 means the least possible compression, smaller values indicate higher compression rations).

Lukas

Am 16.01.2017 um 19:57 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Using the python-test branch:

$ make check

...

TestConversions: Sipi should convert LeavesC.jp2 to JPG F

...

E           conftest.SipiTestError: Downloaded image /tmp/tmp_oh23btb.jpg is different from expected image /home/benjamin/git/Sipi/test/_test_data/images/knora/LeavesC.jpg (wrote /home/benjamin/git/Sipi/test/sipi.log):
E           Image Difference (MeanAbsoluteError):
E                      Normalized    Absolute
E                     ============  ==========
E                Red: 0.0000011204        0.1
E              Green: 0.0000012358        0.1
E               Blue: 0.0000016248        0.1
E              Total: 0.0000013270        0.1

**Comment by benjamingeer** [comment]
OK, but the strange thing is that the error is 0.0 on Mac OS X, and 0.1 on Ubuntu. Can that be right?

**Comment by lrosenth** [comment]
This is strange… On a first sight shouldn’t… 😠

Am 16.01.2017 um 22:35 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


OK, but the strange thing is that the error is 0.0 on Mac OS X, and 0.1 on Ubuntu. Can that be right?
